name: Deploy to Dev Environment

on:
  pull_request:
    branches: [dev]

jobs:
  deploy_approval:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - name: Debug event payload
        run: echo "${{ toJson(github.event) }}"
        
      - name: Access specific input values
        run: |
          echo "Source Branch: ${{ github.event.pull_request.head.ref }}"
          echo "Target Branch: ${{ github.event.pull_request.base.ref }}"
      
      - name: Request approval
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { data: pullRequest } = await github.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number
            });

            if (pullRequest.state === 'open') {
              const reviewers = pullRequest.requested_reviewers.map(reviewer => reviewer.login);
              await github.pulls.requestReviewers({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: context.payload.pull_request.number,
                reviewers: reviewers
              });
            }
      
      - name: Push branch
        run: |
          git checkout origin/${{ github.event.pull_request.head.ref }}
          git push origin ${{ github.event.pull_request.base.ref }}
