name: Deploy to Dev Environment

on:
  pull_request:
    branches: [dev]

jobs:
  deploy_approval:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'

    inputs:
      reviewers:
        description: 'Comma-separated list of reviewers'
        required: true
      source_branch:
        description: 'Source branch'
        required: true
      target_branch:
        description: 'Target branch'
        required: true

    steps:
      - name: Request approval
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { data: pullRequest } = await github.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number
            });

            if (pullRequest.state === 'open') {
              const reviewers = "${{ github.event.inputs.reviewers }}".split(',');
              await github.pulls.requestReviewers({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: context.payload.pull_request.number,
                reviewers: reviewers
              });
            }

      - name: Push branch
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git checkout ${{ github.event.inputs.source_branch }}
          git push origin ${{ github.event.inputs.target_branch }}
